version: "3.8"

services:
  admin:
    build:
      target: install
    user: 1000:1000
    ports:
      - 8001:8000
    command: yarn workspace @kegbot/admin run develop -H 0.0.0.0
    volumes:
      - ./:/app
